site/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
        return view('index');
});

Route::get('/index', function () {
        return view('index');
});

Route::get('/page2', function () {  
	return view('page2');
});

Route::get('/page3', function () {  
	return view('page3');
});

Route::resource('/student', 'StudentController');

site/app/Models/Student.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Student extends Model{
	protected $table = 'student';
	public $timestamps = false;
	
}
?>

site/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

site/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

site/app/Http/Controllers/StudentController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Student;
use Redirect;
use Input;
class StudentController extends Controller{

	public function index(){
		//echo "this is index";
		//return view('student_index');
		
		$student = Student::paginate(5);
		//echo '<pre>';
		//print_r($student -> toArray());	
		//die();
		return view('student_index', compact('student') );	
	}
	public function create(){
		return view('student_create');
	}
	// insert data
	public function store(Request $request){
		//print_r($request -> all());
		//echo $request -> student_name; 
		//die();		
		$student            = new Student();
		$student -> name    = $request -> student_name;
		$student -> address = $request -> student_address;
		$student -> save();
		return redirect() -> route('student_index');	
	}
	public function edit($id)
	{
		$student = Student::find($id);
		//print_r($student -> toArray());
		//die();	
		return view('student_edit', compact('student'));
	}
	public function update(Request $request, $id)
	{
		//echo $id;
		//echo '<pre>';
		//print_r($request -> all());
		$student = Student::find($id);
		$student -> name    = $request -> student_name;
		$student -> address = $request -> student_address;
		$student -> save();
		return redirect() -> route('student_index');	
	}
	public function destroy($id)
	{
		$student = Student::find($id);
		$student -> delete();
		return redirect() -> route('student_index');
	}
}
?>

site/resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MyChoco</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="css/main.css">

</head>
<body>
    <div class="wraper">
    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div class="container">
        	<div class="row">
        		<div class="bs-example">
        		    <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
								<li class="items-choco"><a href="" class="link_main"></a>
								 </li>
								<li class="items-chocomart"><a href="chocomart.kz" title="">.</a></li>
								<li class="items-chocotravel"><a href=""></a></li>
								<li class="items-optic"><a href=""></a></li>
								<li class="items-chocofood"><a href=""></a></li>
								<li class="items-doctor"><a href=""></a></li>
            </ul>
         
            <ul class="nav navbar-nav navbar-right">
                <li><button  class="registration_but type="submit" class="btn btn-default">Регистрация</button></li>
                <li><a class="enter_t" href="/student">Вход</a>
               
            </ul>
            </div>
        	</div>
        </div>
         </div>
    </nav>
</div>
<div class="container">
 <div class="row">
 	<div class="bs-example">
 	  <div class="col-md-2" >
 	  	<div class="btn-group">
  <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Алматы</button>
  <ul class="dropdown-menu">
    <li><a href="#">Пункт 1</a></li>
    <li><a href="#">Пункт 2</a></li>
    <li class="divider"></li>
    <li><a href="#">Пункт 3</a></li>
  </ul>
</div></div>
  <div class="col-md-2" id="col">
  	<div class="faq_block">
      	<div class="faq-icon"></div>
      	<p class="text-faq">НУЖНА ПОМОЩЬ?</p>
      </div></div>
  <div class="col-md-2" id="col"><div class="faq_block">
      	<div class="faq-icon1"></div>
      	<p class="text-faq">ЗАЩИТА ПОКУПАТЕЛЕЙ</p>
    </div></div>
  <div class="col-md-2" left>		 	<div class="faq_block">
      	<div class="faq-icon2"></div>
      	<p class="text-faq">ОБРАТНАЯ СВЯЗЬ</p>
     
    </div></div>
    		<div class="logo-wraper">
	<div class="choco-logo">
		<a href="">
			<span class="b-choco-logo"></span>
		</a>
		<p class="logo-text">
			Главное, чтобы Вы
              <br>были счастливы!
		</p>
	</div>
</div>
<div class="search-wrap">
	<div class="b-search">
		<form action="search" class="b-search-plase">
			<input type="search" placeholder="Найти среди 622 акций" class="search-input">
			<button type="submit" class="e-submit"></button>
		</form>
	</div>
</div>
</div>
<div class="banner-block">
	<span class="closer"></span>
	<div class="b-banner">
		<img src="img/banner.jpg" alt="" class="banner">
	</div>
</div>

</div>
</div>
<div class="category_nav">
	 <div class="bs-example">
	 	<div class="menu_nav_container"> 
	 		  	<ul class="menu_nav">
								<li class="category_li" ><a href="" >Все</a> </li>								      
								<li class="category_li"><a href="" >Новые</a></li>
								<li class="category_li" ><a href="">Хиты продаж</a></li>
								<li class="category_li" ><a href="">Развлечения и отдых</a></li>
								<li class="category_li" ><a href="">Красота и здоровье</a></li>
								<li class="category_li" ><a href="">Спорт</a></li>
								<li class="category_li" ><a href="">Товары</a></li>
								<li class="category_li" ><a href="">Услуги</a></li>
								<li class="category_li" ><a href="">Еда</a></li>
								<li class="category_li" ><a href="">Туризм,отели</a></li>
            </ul></div>
 	   
 </div>
</div>
<div class="b-board">
	<div class="container">
<div class="row">
	<div class="bs-example">
		<div class="block-wrapper">
	
		<div class="col-md-3"><a href=""><img src="img/under_nav.PNG"></a></div>
		<div class="col-md-3"><a href=""><img src="img/under_nav.PNG"></a></div>
		<div class="col-md-3"><a href=""><img src="img/under_nav.PNG"></a></div>
		<div class="col-md-3"><a href=""><img src="img/under_nav.PNG"></a></div>
	</div>
	</div>
</div>

	</div>
</div>
<div class="container">
	<div class="bs-example">
		<div class="b-sort">
			<div class="table-responsive">
<table class="table">
<tbody>
<tr>
<td>Сортировать:</td>
<td><input type="radio">
популярные</td>
<td><input type="radio">цена</td>
<td><input type="radio">скидка</td>
<td><input type="radio">новые</td>
<td><input type="radio">рейтинг</td>
</tr>
</tbody>
</table>
</div>
		</div>
	</div>
	
</div>
<div class="container">
	<div class="row">
		<div class="bs-example">
			<div class="col-md-4"><a href="/page2"><img src="img/39540.jpg" alt=""></a>
			</div>
			<div class="col-md-4"><a href="/page2"><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href="/page2"><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href="/page3"><img src="img/39540.jpg" alt=""></a>
			</div>
			<div class="col-md-4"><a href="/page3"><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href="/page3"><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href=""><img src="img/39540.jpg" alt=""></a>
			</div>
			<div class="col-md-4"><a href=""><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href=""><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href=""><img src="img/39540.jpg" alt=""></a>
			</div>
			<div class="col-md-4"><a href=""><img src="img/39540.jpg" alt=""></a></div>
			<div class="col-md-4"><a href=""><img src="img/39540.jpg" alt=""></a></div>
		</div>
	</div>
</div>
<div class="load-more">
	<span class="e-mainpage_load-more">Показать остальные акции</span>
</div>
<div class="inf-block">
	<div class="container">
		<div class="row">
			<div class="bs-example">
			<div class="col-md-3"><div class="block-img"><img src="img/1.jpg" alt=""></div>
		</div>
		<div class="col-md-7"><h2 style="font-size: 100% !important;
    text-transform: uppercase;">Все скидки и&nbsp;акции в&nbsp;одном месте!</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia excepturi maxime minus aut, vel perspiciatis cum deserunt exercitationem eos, inventore eveniet facilis assumenda quis veritatis, dolorum hic reiciendis! Unde, veritatis!</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia excepturi maxime minus aut, vel perspiciatis cum deserunt exercitationem eos, inventore eveniet facilis assumenda quis veritatis, dolorum hic reiciendis! Unde, veritatis!</p>
</div>

	 </div>
		</div>
		<div class="bs-example">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia excepturi maxime minus aut, vel perspiciatis cum deserunt exercitationem eos, inventore eveniet facilis assumenda quis veritatis, dolorum hic reiciendis! Unde, veritatis!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia excepturi maxime minus aut, vel perspiciatis cum deserunt exercitationem eos, inventore eveniet facilis assumenda quis veritatis, dolorum hic reiciendis! Unde, veritatis!
			</p>

		</div>
	</div>
</div>
<footer id="myFooter">
        <div class="container">
            <div class="row">
            	   <div class="col-sm-1">
                 
                </div>
                    <div class="col-sm-2">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
      
                <div class="col-sm-3">
                    <div class="social-networks">
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                    </div>
                 
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>© 2016 Copyright Text </p>
        </div>
    </footer>
</body> 
</html>

site/resources/views/page2.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MyChoco</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="css/main.css">

</head>
<body>
 
    	 <div class="wraper">
    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div class="container">
        	<div class="row">
        		<div class="bs-example">
        		    <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
								<li class="items-choco"><a href="" class="link_main"></a>
								 </li>
								<li class="items-chocomart"><a href="chocomart.kz" title="">.</a></li>
								<li class="items-chocotravel"><a href=""></a></li>
								<li class="items-optic"><a href=""></a></li>
								<li class="items-chocofood"><a href=""></a></li>
								<li class="items-doctor"><a href=""></a></li>
            </ul>
         
            <ul class="nav navbar-nav navbar-right">
                <li><button  class="registration_but type="submit" class="btn btn-default">Регистрация</button></li>
                <li><a class="enter_t" href="">Вход</a>
               
            </ul>
            </div>
        	</div>
        </div>
         </div>
    </nav>
</div>
				
<div class="container">
 <div class="row">
 	<div class="bs-example">
 	  <div class="col-md-2" >
 	  	<div class="btn-group">
  <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Алматы</button>
  <ul class="dropdown-menu">
    <li><a href="#">Пункт 1</a></li>
    <li><a href="#">Пункт 2</a></li>
    <li class="divider"></li>
    <li><a href="#">Пункт 3</a></li>
  </ul>
</div></div>
  <div class="col-md-2" id="col">
  	<div class="faq_block">
      	<div class="faq-icon"></div>
      	<p class="text-faq">НУЖНА ПОМОЩЬ?</p>
      </div></div>
  <div class="col-md-2" id="col"><div class="faq_block">
      	<div class="faq-icon1"></div>
      	<p class="text-faq">ЗАЩИТА ПОКУПАТЕЛЕЙ</p>
    </div></div>
  <div class="col-md-2" left>		 	<div class="faq_block">
      	<div class="faq-icon2"></div>
      	<p class="text-faq">ОБРАТНАЯ СВЯЗЬ</p>
     
    </div></div>
    		<div class="logo-wraper">
	<div class="choco-logo">
		<a href="">
			<span class="b-choco-logo"></span>
		</a>
		<p class="logo-text">
			Главное, чтобы Вы
              <br>были счастливы!
		</p>
	</div>
</div>
<div class="search-wrap">
	<div class="b-search">
		<form action="search" class="b-search-plase">
			<input type="search" placeholder="Найти среди 622 акций" class="search-input">
			<button type="submit" class="e-submit"></button>
		</form>
	</div>
</div>
</div>
<div class="banner-block">
	<span class="closer"></span>
	<div class="b-banner">
		<img src="img/banner.jpg" alt="" class="banner">
	</div>
</div>

</div>
</div>
<div class="category_nav">
	 <div class="bs-example">
	 	<div class="menu_nav_container"> 
	 		  	<ul class="menu_nav">
								<li class="category_li" ><a href="" >Все</a> </li>								      
								<li class="category_li"><a href="" >Новые</a></li>
								<li class="category_li" ><a href="">Хиты продаж</a></li>
								<li class="category_li" ><a href="">Развлечения и отдых</a></li>
								<li class="category_li" ><a href="">Красота и здоровье</a></li>
								<li class="category_li" ><a href="">Спорт</a></li>
								<li class="category_li" ><a href="">Товары</a></li>
								<li class="category_li" ><a href="">Услуги</a></li>
								<li class="category_li" ><a href="">Еда</a></li>
								<li class="category_li" ><a href="">Туризм,отели</a></li>
            </ul></div>
 	   
 </div>
</div>
<div class="container">
	<div class="bs-example">
		<div class="b-sort">
			<div class="table-responsive">
<table class="table">
<tbody>
<tr>
<td>Сортировать:</td>
<td><input type="radio">
популярные</td>
<td><input type="radio">цена</td>
<td><input type="radio">скидка</td>
<td><input type="radio">новые</td>
<td><input type="radio">рейтинг</td>
</tr>
</tbody>
</table>
</div>
		</div>
	</div>
	
</div>
<div class="container">
	<div class="row">
	<div class="offer-block">
		<div class="offer-top">sfasdfdsfdsfds</div>
		<h1 class="title">Экстремально круто! Абсолютно новый снежный склон ждет вас! Катания на лыжах и сноуборде для взрослых и детей со скидкой до 30% в СРК Табаган!</h1>
  <div class="row">

  	  <div class="col-xs-12 col-sm-6 col-md-8">
  	  	<div class="slider">
  	  		<div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
  <!-- Индикаторы для карусели -->
  <ol class="carousel-indicators">
    <!-- Перейти к 0 слайду карусели с помощью соответствующего индекса data-slide-to="0" -->
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <!-- Перейти к 1 слайду карусели с помощью соответствующего индекса data-slide-to="1" -->
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <!-- Перейти к 2 слайду карусели с помощью соответствующего индекса data-slide-to="2" -->
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>   
  <!-- Слайды карусели -->
  <div class="carousel-inner">
    <!-- Слайды создаются с помощью контейнера с классом item, внутри которого помещается содержимое слайда -->
    <div class="active item">
      <div class="carousel-caption">
        <p>Текст (описание) 1 слайда...</p>
      </div>
    </div>
    <!-- Слайд №2 -->
    <div class="item">
      <div class="carousel-caption">
        <h3>Second slide label</h3>
        <p>Aliquam sit amet gravida nibh, facilisis gravida odio.</p>
      </div>
    </div>
    <!-- Слайд №3 -->
    <div class="item">
      <div class="carousel-caption">
        <h3>Third slide label</h3>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </div>
  </div>
  <!-- Навигация для карусели -->
  <!-- Кнопка, осуществляющая переход на предыдущий слайд с помощью атрибута data-slide="prev" -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <!-- Кнопка, осуществляющая переход на следующий слайд с помощью атрибута data-slide="next" -->
  <a class="carousel-control right" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
  	  	</div>
  	  

  	  </div>
  <div class="col-xs-6 col-md-4">
  	
  	<p class="price">от 1 400 тг.</p>
  	<p class="bought_price">Купили 2396 человек</p>
  	<a href="#" class="e-button">
          <span>Купить</span>
    </a>
  </div>
</div>
	</div>

</div>
</div>
<div class="container">
	<div class="row">
	<div class="offer-block">
		<div class="offer-top-2">
			<ul class="nav nav-pills">
  <li class="active">
    <a href="#">Информация</a>
  </li>
  <li><a href="#">Отзывы</a></li>
  <li><a href="#">Вопросы 157</a></li>
      <li><a href="#">Получить 5000 тенге</a></li>
        <li><a href="#">Как воспользоваться акцией?</a></li>
</ul>
		</div>
<div class="row">
  <div class="col-md-6">
  	<div class="information">
  		<a href="/chocopromise#extended" class="extended_defense">
                        <div class="extended_defense_img"></div>
                        <p class="extended_defense_txt">Расширенная защита покупателей</p>
                    </a>
  		<div class="text-inf">
  			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque a vitae, ipsum incidunt quaerat quos laborum ad expedita dolorem quae, molestiae, quam odio nostrum reprehenderit natus sit quasi blanditiis maiores.</p>
  		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error maxime laboriosam ea placeat earum rem provident minus iste, consequuntur optio id odit deleniti, doloremque expedita, officia, facere ipsum ducimus non!</p> 
  		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas, temporibus! Consequuntur harum, dicta eius rem minus modi atque repudiandae dolor sed. Suscipit illo beatae ullam mollitia quam officiis pariatur laboriosam!</p>
  		</div>
  	</div>

  </div>
  <div class="col-md-6">
  	<div class="video"><iframe width="560" height="315" src="https://www.youtube.com/embed/CIMOwbK8axo" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
  	
  	<div class="b-offer__features">
  		<p class="e-offer__features">Особенности:</p>
       <ul class="b-offer__features-list">
       	<li class="e-offer__feature">Спортивно-развлекательный комплекс «<strong>Табаган</strong>» приглашает вас провести незабываемый зимний отдых с друзьями и близкими.<br>
Готовы к приключениям? Здесь Вас ждут головокружительные склоны, бодрящий морозный воздух и новые трассы для катания на лыжах и сноуборде. Здесь, у подножья гор Заилийского Алатау, вы также найдете пешие тропы для любителей длительных прогулок, отдельные дорожки для велосипедистов и мотоциклистов, для удобства передвижения и наслаждения шикарными видами – канатную дорогу, уютнейшие финские беседки с пылающим камином и песнями под гитару и многое-многое другое.</li>
       </ul>
  	</div>


  </div>
</div>
<div class="b-offer__bottom">
	<div class="b-offer__howpay">
                <span class="b-offer__howpay-text">Способы оплаты:</span>
                <span class="b-offer_visa"></span>
                <span class="b-offer_mastercard">&nbsp;</span>
                                    <span class="b-offer_qiwi">&nbsp;</span>
                            </div>
                            <div class="e-offer__button__bottom">
                            	<a href="">Купить</a>
                            </div>

</div>
</div>
	</div>

</div>
</div>

<footer id="myFooter">
        <div class="container">
            <div class="row">
            	   <div class="col-sm-1">
                 
                </div>
                    <div class="col-sm-2">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
      
                <div class="col-sm-3">
                    <div class="social-networks">
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                    </div>
                 
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>© 2016 Copyright Text </p>
        </div>
    </footer>
</body> 
</html>

site/resources/views/student_create.blade.php
<form action="<?php echo route('student.store') ?>" method="post">
<!--  -->
<?php
echo csrf_field()
?>
Name <input type="text" name="student_name" />
<br>
Adress <input type="text" name="student_address" />
<br>
<input type="submit" value="Save"/>
</form>

site/resources/views/student_edit.blade.php
<form action="<?php echo route('student.update', $student -> id) ?>" method="post">
<!--  -->
<?php
echo csrf_field();
echo method_field('PATCH');
?>
Name <input type="text" name="student_name" value="<?php echo $student -> name ?>" />
<br>
Address <input type="text" name="student_address" value="<?php echo $student -> address?>" />
<br>
<input type="submit" value="Save"/>
</form>

site/resources/views/student_index.blade.php
<a href='<?php echo route('student.create'); ?>' >Create</a>
<br><br>
<table border="1">
	<tr>
		<th>No</th>
		<th>Title</th>
		<th>text</th>
		<th>Action</th>
	</tr>
	<tr>
	<?php
	$s = 1;
		foreach($student as $key => $value){
	?>
	<tr>
		<td><?php echo $value -> id?></td>		
		<td><?php echo $value -> name    ?></td>
		<td><?php echo $value -> address ?></td>
		<td>
			<a href='<?php echo route('student.edit', $value -> id); ?>' >Edit</a>
			&nbsp; 
			<form action="<?php echo route('student.destroy', $value -> id); ?>" method="post" style="display: inline-block;">
			<?php echo method_field('DELETE'); ?>			
			<?php echo csrf_field();  ?>			
			 
				<a href="javascript:;" onclick="confirm_delete(this.parentNode)" > Delete </a>
			</form>
		</td>
	</tr>		
	<?php
	}
	?>
	</tr>
</table>

{!! $student->render() !!}
<style type="text/css">
li{
	list-style: none;
	display: inline-block;
}
</style>
<script type="text/javascript">
	function confirm_delete(form)
	{
		c = confirm('Delete data?');
		//alert("test");
		if(c == true)
		{
			form.submit();
		}else
		{
			//do nothing	
		}
			
	}
</script>